spring:
  application:
    name: modulo2.1

  cors:
    urls: "*"

  cloud:
    gateway:
      routes:
        - id: modulo1
          uri: ${MODULO1_URI}
          predicates:
            - Path=/anajulia/modulo1/**

        - id: modulo2_2
          uri: ${MODULO2_2_URI}
          predicates:
            - Path=/anajulia/modulo2.2/**

server:
  port: 8080

secret:
  key: ${SECRET_KEY}