spring:
  application:
    name: modulo2.1

  cors:
    urls: "*"

  cloud:
    gateway:
      routes:
        - id: modulo1
          uri: http://localhost:8082
          predicates:
            - Path=/anajulia/modulo1/**

        - id: modulo2.2
          uri: http://localhost:8081
          predicates:
            - Path=/anajulia/modulo2.2/**

server:
  port: 8080

secret:
  key: "o36pEukmNV48mJkKkRt8GoYtfbXfszupz6Zrq6jPAEC"